# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
group :development, :test do
  gem "rubocop", require: false
  gem "rspec"  , require: false
  gem 'rainbow', require: false
end